//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int AdminId { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
}

public partial class CardInfo
{
    public int CardInfoId { get; set; }
    public Nullable<int> PokerOrder { get; set; }
    public string Name { get; set; }
    public string Image { get; set; }
}

public partial class Hand
{
    public int UserId { get; set; }
    public int CardId { get; set; }
}

public partial class User
{
    public int user_id { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public int wins { get; set; }
    public int losses { get; set; }
    public int draws { get; set; }
    public int blackjack { get; set; }
    public int highscore { get; set; }
    public string cc_number { get; set; }
    public decimal balance { get; set; }
}
